# Generated by Django 4.1 on 2022-08-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('cityname', models.CharField(max_length=255)),
                ('streetname', models.CharField(max_length=255)),
                ('housecode', models.IntegerField(max_length=32)),
                ('citycode', models.IntegerField(max_length=32)),
                ('isadult', models.BooleanField()),
                ('levelofeducation', models.CharField(max_length=128)),
                ('currentproffession', models.CharField(max_length=128)),
            ],
        ),
    ]
